### ISSUE TITLE
Feature request: Add --subnet flag in datalab create

### ISSUE THREAD

**Issue by charlesverdad** [googledatalab/datalab#1924]
I want to attach my datalab instance into a subnetwork I created but I can't find a way to do it. The `gcloud compute instances create` command has a `--subnet` flag. It would be great if that same flag can be used in the `datalab create` command.

> --subnet=SUBNET
> Specifies the subnet that the instances will be part of. If --network is also specified subnet must be a subnetwork of network specified by --network.
> 

**EDIT**: added additional info below
If the VPC network is in custom mode, there's currently no way to create a datalab instance into that network because it gives this error:
```
Creating the instance my-datalab
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - Invalid value for field 'resource.networkInterfaces[0]': ''. Subnetwork should be specified for custom subnetmode network
A nested call to gcloud failed.
```

**Comment by chmeyers** [comment]
This is basically https://github.com/googledatalab/datalab/issues/1535 but "even more options".  I think this is more evidence that we should just allow arbitrary pass-through arguments that go straight to 'gcloud compute instances create'

**Comment by nikhilk** [comment]
Would we need some options for creating an instance, vs. some for connecting, vs. some for creating the repo, or any of the N steps we do etc? At the risk of complicating things with generalization, maybe we need a --create-flags and a --connect-flags, and so on?

**Comment by charlesverdad** [comment]
I like the --create-flags and --connect-flags options.

Update:
Because I converted my main VPC network into custom subnet mode (irreversible), I can no longer create datalab instances that are connected to my main instances. I can't even make a separate VPC network set to auto and use VPC peering because their subnets overlap.

**Comment by chmeyers** [comment]
FYI charlesverdad if you are blocked while we are debating this, you can grab a copy of the create command from https://github.com/googledatalab/datalab/blob/master/tools/cli/commands/create.py#L746 and edit it to specify a subnet (at around line 746).

**Comment by ojarjur** [comment]
This is now fixed with version 214.0.0 of the Cloud SDK

**Comment by HeshamMahrous** [comment]
I updated gcloud componets to the latest 214 and it still get Creating the instance hesh
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - Invalid value for field 'resource.networkInterfaces[0]': ''. Subnetwork should be specified for custom subnetmode network

A nested call to gcloud failed, use --verbosity=debug for more info.
