### ISSUE TITLE
gcloud configuration may not be cached

### ISSUE THREAD

**Issue by parthea** [googledatalab/datalab#856]
After pulling the latest master, the gcloud configuration does not appear to be cached from outside the container (or I may have a configuration issue somewhere). 

On my host machine,
```
tony@tonypc:~/Git/datalab-parthea/containers/datalab$ gcloud config list
Your active configuration is: [default]

[compute]
region = us-east1
zone = us-east1-d
[core]
account = tonypartheniou@XXXX
disable_usage_reporting = True
project = XXXX
```

In the datalab container,

```
root@XXXXX:/# gcloud config list
Your active configuration is: [default]

[core]
disable_usage_reporting = True
`````

After running cloud init in the container, and going through the login process, I see the following
```
root@XXXXX:/# gcloud config list
Your active configuration is: [default]

[compute]
region = us-east1
zone = us-east1-d
[core]
account = tonypartheniou@XXXX
disable_usage_reporting = True
project = XXXX
```

When I stop the container and start it again, the gcloud configuration does not appear to be cached outside the container.

```
root@XXXXX:/# gcloud config list
Your active configuration is: [default]

[core]
disable_usage_reporting = True

```

From #804 ,
> ...Because we set it to a location in the mapped in volume the credentials will get cached outside the container, so if you restart the container you don't have to go through auth flow again.

**Comment by gramster** [comment]
Are you starting it with the run.sh script in containers/datalab? Inside the container, what are your environment variable values?

**Comment by parthea** [comment]
> Are you starting it with the run.sh script in containers/datalab?

Yes. I am starting it using `PROJECT_ID=my-project-id` ./run.sh

> Inside the container, what are your environment variable values?

I have not set any other environment variables other than `PROJECT_ID` . Do I need to set `GOOGLE_APPLICATION_CREDENTIALS`?

**Comment by parthea** [comment]
From [Datalab Getting Started](https://github.com/GoogleCloudPlatform/datalab/wiki/Getting-Started),
> The first time you open Datalab you will have to accept the EULA.

I didn't get a EULA page (although I have seen it before)

**Comment by gramster** [comment]
No, the one I am interested in is GCLOUDSDK_CONFIG

**Comment by gramster** [comment]
The acceptance is cached.

**Comment by parthea** [comment]
I found that GCLOUDSDK_CONFIG is not set

```
> !echo $DATALAB_ENV
local
```

```
!echo $GCLOUDSDK_CONFIG

```

**Comment by gramster** [comment]
What about DATALAB_ENV?

You should be seeing:

DATALAB_ENV=local
CLOUDSDK_CONFIG=/content/datalab/.config

Does /datalab/setup-env.sh exist?

**Comment by parthea** [comment]
My mistake, I typed `GCLOUDSDK_CONFIG` instead of `CLOUDSDK_CONFIG`

I have
```
DATALAB_ENV=local
CLOUDSDK_CONFIG=/content/datalab/.config
```

Yes `/datalab/setup-env.sh` exists

**Comment by gramster** [comment]
Okay, so the next question is, in your home directory outside the
container, do you have a ~/datalab/.config directory? That is where the
credentials and configuration should be cached.

**Comment by parthea** [comment]
I have the `~/datalab/.config` directory, but it is empty
```
tony@tony-laptop:~/datalab/.config$ ls -a
.  ..
```

**Comment by parthea** [comment]
I also noticed an error related creating the `.config` folder on another machine that I was testing

```
tony@TonyLinuxDesktop:~/datalab-parthea/containers/datalab$ ./run.sh
./run.sh: 40: [: unexpected operator
mkdir: cannot create directory '/content/datalab/.config': File exists
From https://github.com/googledatalab/notebooks
 * branch            master     -> FETCH_HEAD
HEAD is now at 6aa65ea Merge pull request #2 from googledatalab/missing
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
{"name":"app","hostname":"XXXXXXXXX","pid":25,"level":30,"msg":"Starting DataLab server at http://localhost:8080","time":"2016-05-20T23:28:54.517Z","v":0}
```

On the fresh install, I didn't see the error

**Comment by gramster** [comment]
Do you see this each time though?

$ ./run.sh
./run.sh: 40: [: unexpected operator

**Comment by gramster** [comment]
I think I know what the problem is. As a workaround, try this:

rm ~/datalab/.config
mkdir ~/datalab/.config

Then run the container.

**Comment by gramster** [comment]
Should be fixed now going forward, but Tony, you will need to do that rm
step to fix yours.

**Comment by parthea** [comment]
> Do you see this each time though?

I always see the `unexpected operator` error.
```
./run.sh: 40: [: unexpected operator
```

The work around resolves the following error, but it does not resolve the missing credentials in .config
```
mkdir: cannot create directory '/content/datalab/.config': File exists
```

**Comment by parthea** [comment]
On the machine with a clean install of datalab, I didn't see the error 
```
mkdir: cannot create directory '/content/datalab/.config': File exists
```

The `~/datalab/.config` folder is still empty

**Comment by parthea** [comment]
I play around this weekend to try and find the issue. We can continue troubleshooting next week if I can't resolve the issue.

**Comment by gramster** [comment]
Did you sign in? On the tree view there is a little sign in icon at the top
right now.

**Comment by parthea** [comment]
aha! I didnt see the sign in button! Its working now! Thanks!

**Comment by parthea** [comment]
Perhaps we could make the sign in button more visible?

**Comment by parthea** [comment]
Also, need to update the [Getting Started](https://github.com/GoogleCloudPlatform/datalab/wiki/Getting-Started) guide , to tell users that they need to sign in.

**Comment by parthea** [comment]
Obsolete. The[ datalab quickstart guide](https://cloud.google.com/datalab/docs/quickstarts/quickstart-local) explains that there is an extra step to sign in.
